### ISSUE TITLE
search_for_apps.py what are it's expectation for Org

### ISSUE THREAD

**Issue by nyue** [athera-io/athera-python#15] opened 2018-11-07 23:04 UTC
Hi,

  Running the example search_for_apps.py, I tried the following without much interesting respond.

  What is the expected Org string ? I thought my default org would work.

=====================

This example will ask for a group, then a string, searching for all app families which contain that string in their name.

It then prints the contained app versions with their type (interactive/compute) and app id.

These app ids can be used during sessions.start_session and compute.make_job_request.

Tested with Python 2.7.15, 3.7.1.

2018-11-08 09:59:40,349 - athera-python - INFO - Getting orgs for user
GET https://api.athera.io/api/v1/orgs [200]
2018-11-08 09:59:41,639 - athera-python - INFO - 0 default-nyue
Select an Org: hello
Select an Org: world
Select an Org: nicholas
Select an Org: athera-python
Select an Org: default-nyue
Select an Org: help
Select an Org: ?
Select an Org: *
Select an Org: houdini
Select an Org: 

Cheers

**Comment by sipickles** [comment] 2018-11-08 13:42
Hello,

Please pull the latest and try again. We've worked to improve the clarity of the process:

https://github.com/athera-io/athera-python/commit/214ed85d1ef37df5f00332053ade096371f5d336

**Comment by nyue** [comment] 2018-11-08 23:01
Gave it another go, now I get the follow error

I tried using the app Toolbox as the name since I know it exists

=============================
This example will ask you to select an Org, then a string, searching for all App families which contain that string in their name.

Only App families for which the Org has an active entitlement are shown.

It then prints the contained app versions with their type (interactive/compute) and app id.

These app ids can be used during sessions.start_session and compute.make_job_request.

Tested with Python 2.7.15, 3.7.1.

Getting orgs for user
GET https://api.athera.io/api/v1/orgs [200]
Selected default-nyue
-- Enter the app name (or part of) to search for: Toolbox
Searching families for Toolbox
GET https://api.athera.io/api/v1/families [403]
Traceback (most recent call last):
  File "search_for_app.py", line 96, in <module>
    main()
  File "search_for_app.py", line 69, in main
    families = searcher.search_families(target)
  File "search_for_app.py", line 32, in search_families
    apps_dict = common.convert_response(apps_response)
  File "/Users/u0079711/projects/Athera/athera-python_git/examples/common.py", line 50, in convert_response
    return response.json()
  File "/Users/u0079711/anaconda3/envs/athera/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/u0079711/anaconda3/envs/athera/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/u0079711/anaconda3/envs/athera/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/u0079711/anaconda3/envs/athera/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sipickles** [comment] 2018-11-09 08:44
Hi,

Did you try a second time?

One thing the examples don't do is retry queries in the event of an error.

I've run this locally and so far cannot reproduce this problem, but we'll add a try/except wrapper round the decoding.

Here's my output:

```
$ python search_for_app.py 
 
This example will ask you to select an Org, then a string, searching for all App families which contain that string in their name.

Only App families for which the Org has an active entitlement are shown.

It then prints the contained app versions with their type (interactive/compute) and app id.

These app ids can be used during sessions.start_session and compute.make_job_request.

Tested with Python 2.7.15, 3.7.1.

Getting orgs for user
GET https://api.athera.io/api/v1/orgs [200]
-- Select an Org
1) ABC
2) Abstract2
3) CoolFX
4) Foundry-AtheraLive
5) Skynet
6) foundry-support
-- 2
Selected Abstract2
-- Enter the app name (or part of) to search for: Toolbox
Searching families for Toolbox
GET https://api.athera.io/api/v1/families [200]
Toolbox                                            9a23674e-9102-44f0-8fe0-c2e27a936f82
-- interactive 0.1.0                               85321d27-f02c-47cc-8253-5a70192c8b7d
```

**Comment by nyue** [comment] 2018-11-09 10:08
Repeated the test 4 times (this time on Linux, previously on OS X), now getting the following error message

====================================
Getting orgs for user
GET https://api.athera.io/api/v1/orgs [200]
Selected default-nyue
-- Enter the app name (or part of) to search for: Toolbox
Searching families for Toolbox
GET https://api.athera.io/api/v1/families [403]
Traceback (most recent call last):
  File "search_for_app.py", line 96, in <module>
    main()
  File "search_for_app.py", line 72, in main
    result = list(filter(lambda f: 'Bundled' not in f['name'], families))
TypeError: 'NoneType' object is not iterable

**Comment by nyue** [comment] 2018-11-09 23:04
The call line 72 

    families = searcher.search_families(target)

failed and returns nothing so the subsequent call fails.

I will add a check and submit a pull request.

Cheers

**Comment by sipickles** [comment] 2018-11-10 08:46
Thanks!

**Comment by sipickles** [comment] 2018-11-12 09:49
PR accepted. Closing.

**Closed by sipickles** 2018-11-12 09:49 UTC
